In [1]:
# H1 TITLE
## H2 TITLE

In [2]:
print("Buy the dip?")

Buy the dip?


In [1]:
import numpy as np
your_np_array = np.array([1, 1.1, "hello", {"number":1}, [1,2,4], (1,2), {1,2}, True], dtype=object)
for i in your_np_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [4]:
a = np.zeros(300)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Create a NumPy array of dimension 300 with zeros without filling it manually
# Reshape it to (3,100)

a = np.zeros(300)
print(a)
#a.reshape(3,100)
print(a.reshape(3, 100))

In [ ]:
# Question 1: Array from 1 to 100
q1 = np.array(range(1, 101))
print(q1)

# Question 2: Odd numbers from 1 to 99
q2 = np.array(range(1, 100, 2))
print(q2)

# Question 3: Even numbers from 100 to 2 (descending)
q3 = np.array(range(100, 1, -2))
print(q3)

# Question 4: 1-100 with multiples of 5 replaced by 0
q4 = q1.copy()
q4[1::3] = 0
print(q4)

In [ ]:
# Random data generation
np.random.seed(888)

# 1D array size 100 with normal distribution
arr1 = np.random.randn(100)
print(arr1.shape)

# 2D array 8x8 with random integers 1-10
arr2 = np.random.randint(1, 11, (8, 8))
print(arr2.shape)

# 3D array 4x2x5 with random integers 1-17
arr3 = np.random.randint(1, 18, (4, 2, 5))
print(arr3.shape)

In [ ]:
# Generate an array with integers from 1 to 50: 
a1 = np.array(range(1,51))
print(a1)

# Generate an array with integers from 51 to 100:
a2 = np.array(range(51,101))
print(a2)

#Using np.concatenate, concatenate the two arrays into
a3 = np.concatenate((a1, a2))
print(a3)

# Reshape the concatenated array into a 10x10 matrix
a4 = a3.reshape(10,10)
print(a4)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  5

In [ ]:

# Create a 9x9 array filled with ones
array1 = np.ones((9,9), dtype=np.int8) 
print(array1)

# Create nested pattern using slicing
arr = np.ones((9, 9), dtype=np.int8)
arr[1:-1, 1:-1] = 0
arr[2:-2, 2:-2] = 1
arr[3:-3, 3:-3] = 0
arr[4, 4] = 1
print(arr)


[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [ ]:
# Broadcasting example
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)

# array_1 has shape (5,)
# array_2 has shape (3,)

# We need to reshape array_1 to be a column vector (shape: 5x1)
# array_2 can remain a row vector (shape: 3,)
# The np.newaxis object adds a new dimension
column_vector = array_1[:, np.newaxis]
# Now, multiply them. NumPy will broadcast the two arrays:
# The (5, 1) array is stretched across 3 columns.
# The (3,) array is stretched down 5 rows.
# The result is a (5, 3) matrix.
output_matrix = column_vector * array_2

print(output_matrix)

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [38]:
generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan
print(grades)

# 1. Create the logic for the third column using np.where.
# The function works like this: np.where(condition, value_if_true, value_if_false)

# Condition: We check which elements in the first column (grades[:, 0]) are NOT NaN.
# The `~` operator inverts the boolean result of np.isnan().
condition = ~np.isnan(grades[:, 0])

# Value if True: If the grade is not NaN, we use the grade from the first column.
value_if_true = grades[:, 0]

# Value if False: If the grade is NaN, we use the grade from the second column.
value_if_false = grades[:, 1]

# The result is a new 1D array containing the final grades.
final_exam_grades = np.where(condition, value_if_true, value_if_false)


# 2. Add this new array as the third column to the original 'grades' array.
# We use np.c_ which is a powerful tool for concatenating arrays along the second axis (columns).
# It correctly handles stacking the 2D 'grades' array with the 1D 'final_exam_grades' array.
grades_with_final = np.c_[grades, final_exam_grades]

print(grades_with_final)


[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]
[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


In [43]:
# Load the data from the CSV file
data = np.genfromtxt('winequality-red.csv', delimiter=';', skip_header=1, dtype=np.float32)

# Get the size of the array in bytes
byte_size = data.nbytes

print(f"The size of the NumPy array is: {byte_size} bytes")

The size of the NumPy array is: 76752 bytes


In [45]:
# "Display the 2nd, 7th, and 12th rows as a two-dimensional array. Exclude np.nan values if present."

rows_to_display = data[[1, 6, 11], :]
print(rows_to_display) 

[[7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00 5.000e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00 5.000e+00]
 [7.500e+00 5.000e-01 3.600e-01 6.100e+00 7.100e-02 1.700e+01 1.020e+02
  9.978e-01 3.350e+00 8.000e-01 1.050e+01 5.000e+00]]
